### ISSUE TITLE
[question] how to use themes?

### ISSUE THREAD

**Issue by kagbodji** [FeiyouG/commander.nvim#25]
Hi there, thanks for this amazing plugin. I would like to understand how to use themes. [The config in the readme](https://github.com/FeiyouG/command_center.nvim#configure) states one can use the command_center theme or any telescope or custom theme, but I don't understand where  `themes` in `theme = themes..command_center` comes from. I also tried using a Telescope default theme, but because I lazy-load telescope, it becomes an chicken-or-egg problem where telescope is not yet loaded before I can `require("telescope.themes")` (at least that's my understanding of the error I'm getting, I'm still relatively new to lua/telescope).

Can you please help shed some like on what I might possibly be doing wrong here? Thanks!

**Comment by FeiyouG** [comment]
Sorry for the confusion, I probably should make it clearer in README. 

You are correct though, you can get the theme from `require("telescope.themes").command_center`. However, since this is the default theme for command_center, you don't need to specify it unless you want to switch to a different theme. If it causes problem with lazy loading, just don't set the field`theme` when you call `setup` or set it to `nil`. 

I hope this hleps.
